### ISSUE TITLE
Ready to copy/paste asciidoc text for project Readme

### ISSUE THREAD

**Issue by lpetit-yseop** [yseop/docker-helper#4]
In addition to providing scripts for starting a project, we could also provide, in this repo, a template of asciidoc snippet to include in the Readme of the project => it would suggest the appropriate structure, pre-filled with sensitive values (links to external doc, basic `== Usage`, etc.)

**Comment by lparet-yseop** [comment]
I think it's a good idea for the example project repository we talked about on this page: https://yseop-knowledge.atlassian.net/wiki/spaces/KNOW/pages/466026613/Git+repository+for+bootstrapping+Jenkins+Pipeline
This repository is just for the docker script.

**Comment by lpetit-yseop** [comment]
Ok, I get your point, and I think you're right. Closing the issue.
